# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gibbs_pliable_lasso_logistic2_rcpp <- function(y, X, Z, n_iter = 2000L, burn_in = 1000L, sigma0_sq = 1.0, eps = 1e-6, clamp_min = 1e-10, clamp_max = 1e10, verbose = TRUE) {
    .Call('_hspliable_gibbs_pliable_lasso_logistic2_rcpp', PACKAGE = 'hspliable', y, X, Z, n_iter, burn_in, sigma0_sq, eps, clamp_min, clamp_max, verbose)
}

gibbs_pliable_lasso_missing_cpp <- function(y_in, X, Z, n_iter = 2000L, burn_in = 1000L, a0 = 1e-2, b0 = 1e-2, sigma0_sq = 1.0, eps = 1e-6, verbose = FALSE, seed = NULL) {
    .Call('_hspliable_gibbs_pliable_lasso_missing_cpp', PACKAGE = 'hspliable', y_in, X, Z, n_iter, burn_in, a0, b0, sigma0_sq, eps, verbose, seed)
}

